import { Game } from '@/types/games'

export const games: Game[] = [
  {
    id: 'snake',
    name: 'Snake',
    description: 'Classic snake game - eat food and grow longer!',
    icon: '🐍',
    bgColor: '#00FF00',
    accentColor: '#39FF14',
    difficulty: 'easy',
    multiplayer: false,
  },
  {
    id: 'parkour',
    name: 'Pixel Parkour',
    description: 'Jump, dash, and defeat bosses in this platformer!',
    icon: '🏃',
    bgColor: '#FF10F0',
    accentColor: '#FF00FF',
    difficulty: 'hard',
    multiplayer: false,
  },
  {
    id: 'pacman',
    name: 'Pac-Runner',
    description: 'Collect dots and avoid ghosts in the maze!',
    icon: '👾',
    bgColor: '#FFFF00',
    accentColor: '#FFD700',
    difficulty: 'medium',
    multiplayer: false,
  },
  {
    id: 'space-invaders',
    name: 'Space Blasters',
    description: 'Defend Earth from alien invaders!',
    icon: '🚀',
    bgColor: '#00D9FF',
    accentColor: '#00FFFF',
    difficulty: 'medium',
    multiplayer: false,
  },
  {
    id: 'tetris',
    name: 'Block Drop',
    description: 'Stack blocks and clear lines!',
    icon: '🟦',
    bgColor: '#9D00FF',
    accentColor: '#9400D3',
    difficulty: 'medium',
    multiplayer: false,
  },
  {
    id: 'pong',
    name: 'Neon Pong',
    description: 'The classic paddle game!',
    icon: '🏓',
    bgColor: '#FF6600',
    accentColor: '#FF4500',
    difficulty: 'easy',
    multiplayer: false,
    comingSoon: true,
  },
  {
    id: 'breakout',
    name: 'Brick Breaker',
    description: 'Smash all the bricks with your ball!',
    icon: '🧱',
    bgColor: '#FF0000',
    accentColor: '#DC143C',
    difficulty: 'easy',
    multiplayer: false,
    comingSoon: true,
  },
]